### GET request to example server
GET https://maps-api.apple.com/v1/token
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IkpURFNYUEJDTVEiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiIyNzU1OThHOThTIiwib3JpZ2luIjoibG9jYWxob3N0IiwibmJmIjoxNzYwMDc1ODI2LCJleHAiOjE3NjAwOTc0MjYsImlhdCI6MTc2MDA3NTgyNiwiaXNzIjoiMjc1NTk4Rzk4UyIsImF1ZCI6ImxvY2FsaG9zdCJ9.6kx9CWsOev-rUYCYctarn0oHGP4TLMkWn_uEih-L6KeW1rnYj1Kx4Pg2sAIiPUQ4iiIUdOv_T7lvgjUWe5x0NA

###
GET https://localhost:7110/hypermedia/z2XP3i1du0GRkLyhkPC-Ag

###
GET https://localhost:7110/hypermedia/cGrCi4e8zUy1wy8tL1eOxA

###
GET https://localhost:7110/Workspaces/b9d1e5c4-ae9b-4695-9fbf-8d61c41afeab/Media/preview/1ffea2ed-4575-42c7-b223-18f383d8cd0c?path=imac-g3.jpg

### Time Widget
GET https://localhost:7110/hypermedia/YdZIOMVbmUSJ8Y7_KWShLg

### Weather Widget
GET https://localhost:7110/hypermedia/5XPj2RFBfkaq1Jpn8jnnRQ

### RssFeed Widget
GET https://localhost:7110/hypermedia/oIZosNZjkkGwH0VU-EnsYA

### RssFeed Widget
GET https://localhost:7110/hypermedia/xdosrEypDEiGvzbq5OJraw
